# Generated by Django 5.2 on 2025-08-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=100)),
                ("rank", models.CharField(max_length=8)),
                ("achievement", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "chart_difficulty",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("calculated_rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OldSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_name", models.CharField(max_length=100)),
                ("rank", models.CharField(max_length=8)),
                ("achievement", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "chart_difficulty",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("calculated_rating", models.IntegerField(default=0)),
            ],
        ),
    ]
