# Generated by Django 5.2 on 2025-08-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_maimaisong"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maimaisong",
            name="dx_lev_adv",
        ),
        migrations.RemoveField(
            model_name="maimaisong",
            name="dx_lev_bas",
        ),
        migrations.RemoveField(
            model_name="maimaisong",
            name="dx_lev_exp",
        ),
        migrations.RemoveField(
            model_name="maimaisong",
            name="dx_lev_mas",
        ),
        migrations.RemoveField(
            model_name="maimaisong",
            name="dx_lev_remas",
        ),
    ]
