# Generated by Django 5.2 on 2025-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_maimaisong_chart_type_alter_maimaisong_lev_adv_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsong",
            name="difficulty_type",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AddField(
            model_name="oldsong",
            name="difficulty_type",
            field=models.CharField(default="", max_length=16),
        ),
    ]
