# Generated by Django 5.2.5 on 2026-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_newsong_difficulty_type_oldsong_difficulty_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="maimaisong",
            name="aliases",
            field=models.TextField(blank=True, null=True),
        ),
    ]
