# Generated by Django 5.2.5 on 2026-05-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_maimaisong_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="maimaisong",
            name="analyzed_skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
